import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-red-hat-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redHatDisplay.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
